[project]
name = "aiogrambot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.24.0",
    "dotenv>=0.9.9",
    "lxml>=6.0.2",
    "requests>=2.32.5",
]
